# Generated by Django 3.2.8 on 2021-10-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('cover_img', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'epics',
            },
        ),
    ]
