# Generated by Django 3.2.8 on 2021-10-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epic',
            name='cover_img',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
    ]
